# Generated by Django 4.0.6 on 2022-10-06 18:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_category_en_news_category_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category_af',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ar_dz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_be',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_bg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_bn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_br',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_bs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_cs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_cy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_da',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_dsb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_el',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_en_au',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_en_gb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_eo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_es_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_es_co',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_es_mx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_es_ni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_es_ve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_et',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_eu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_fa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_fy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_gd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_gl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_he',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_hi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_hr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_hsb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_hu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_hy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_io',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_is',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_it',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_kab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_kk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_km',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_kn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_lb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_lt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_lv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_mk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ml',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_mn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_mr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_my',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_nb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_nl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_nn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_pa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_pl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_pt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_pt_br',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_sk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_sl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_sq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_sr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_sr_latn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_sv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_sw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_te',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_tg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_th',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_tk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_tt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_udm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_ur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_vi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_zh_hans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='category_zh_hant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_af',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ar_dz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ast',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_be',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_bg',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_bn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_bs',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ca',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_cs',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_cy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_da',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_dsb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_el',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en_au',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en_gb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_eo',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_es_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_es_co',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_es_mx',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_es_ni',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_es_ve',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_et',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_eu',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_fi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_fy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ga',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_gd',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_gl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_he',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_hi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_hr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_hsb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_hu',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ia',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ig',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ind',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_io',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_is',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ja',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ka',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_kab',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_km',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_kn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ko',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ky',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_lb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_lt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_lv',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_mk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ml',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_mn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_mr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ms',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_my',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_nb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ne',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_nl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_nn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_os',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_pa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_pl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ro',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_sk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_sl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_sq',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_sr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_sr_latn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_sv',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_sw',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ta',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_te',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_tg',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_th',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_tk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_tt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_udm',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ur',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_vi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_zh_hans',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_zh_hant',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_af',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar_dz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ig',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kab',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_af',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ar_dz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_bs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_cs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_cy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_da',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_dsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_el',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_en_au',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_en_gb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_eo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_es_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_es_co',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_es_mx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_es_ni',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_es_ve',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_et',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_eu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_fy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_gd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_gl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_hr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_hsb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_hu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_hy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_io',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_is',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_it',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ka',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_kab',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_km',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_kn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_lb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_lt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_lv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_mk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ml',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_mn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_mr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_my',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_nb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_nn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_pa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_sk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_sl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_sq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_sr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_sr_latn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_sv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_te',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_tg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_tk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_tt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_udm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_vi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_zh_hant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
