# Generated by Django 4.0.6 on 2022-09-30 07:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthotel',
            name='address_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='abouthotel',
            name='address_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='abouthotel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='abouthotel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='abouthotel',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='abouthotel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extraservicesinfo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='extraservicesinfo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='extraservicesinfo',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraservicesinfo',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraservicespoints',
            name='points_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraservicespoints',
            name='points_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelfacilities',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='hotelfacilities',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='hotelfacilities',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelfacilities',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
