# Generated by Django 4.0.6 on 2022-10-06 18:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubs_description_en_clubs_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='description_af',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ar_dz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ast',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_be',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_bg',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_bn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_bs',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ca',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_cs',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_cy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_da',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_dsb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_el',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_en_au',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_en_gb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_eo',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_es_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_es_co',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_es_mx',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_es_ni',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_es_ve',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_et',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_eu',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_fi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_fy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ga',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_gd',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_gl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_he',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_hi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_hr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_hsb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_hu',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ia',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ig',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ind',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_io',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_is',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ja',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ka',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_kab',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_km',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_kn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ko',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ky',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_lb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_lt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_lv',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_mk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ml',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_mn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_mr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ms',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_my',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_nb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ne',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_nl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_nn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_os',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_pa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_pl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ro',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_sk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_sl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_sq',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_sr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_sr_latn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_sv',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_sw',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ta',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_te',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_tg',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_th',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_tk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_tt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_udm',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_ur',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_vi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_zh_hans',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='description_zh_hant',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_af',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ar_dz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ig',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_kab',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_tg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_tk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_af',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ar_dz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ast',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_be',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_bg',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_bn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_bs',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ca',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_cs',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_cy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_da',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_dsb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_el',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_en_au',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_en_gb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_eo',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_es_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_es_co',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_es_mx',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_es_ni',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_es_ve',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_et',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_eu',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_fi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_fy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ga',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_gd',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_gl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_he',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_hi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_hr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_hsb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_hu',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ia',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ig',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ind',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_io',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_is',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ja',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ka',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_kab',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_km',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_kn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ko',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ky',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_lb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_lt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_lv',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_mk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ml',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_mn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_mr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ms',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_my',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_nb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ne',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_nl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_nn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_os',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_pa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_pl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ro',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_sk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_sl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_sq',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_sr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_sr_latn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_sv',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_sw',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ta',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_te',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_tg',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_th',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_tk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_tt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_udm',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_ur',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_vi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_zh_hans',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='description_zh_hant',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_af',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ar_dz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ig',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_kab',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_tg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_tk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubsinfo',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_af',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ar_dz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_be',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_bs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ca',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_cy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_da',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_dsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_el',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_en_au',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_en_gb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_eo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_es_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_es_co',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_es_mx',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_es_ni',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_es_ve',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_et',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_eu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_fi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_fy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_gd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_gl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_hr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_hsb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_hu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ig',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ind',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_io',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_is',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_it',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ja',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ka',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_kab',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_km',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_kn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_lb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_lt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_lv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_mn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_my',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ne',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_nn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_pa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_sk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_sl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_sr_latn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_sv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_sw',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_te',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_tg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_th',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_tk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_tt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_udm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spaetiquette',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
