# Generated by Django 4.0.4 on 2022-09-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotelbooking',
            unique_together=set(),
        ),
    ]
