# Generated by Django 4.0.6 on 2022-09-30 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('booking', '0002_alter_hotelbooking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotelbooking',
            unique_together={('check_in', 'check_out', 'room')},
        ),
    ]
