# Generated by Django 4.0.4 on 2022-09-12 10:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amenitiesIcon', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(unique=True)),
                ('room', models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='rooms/')),
                ('price', models.PositiveIntegerField()),
                ('for_persons', models.PositiveIntegerField()),
                ('for_children', models.PositiveIntegerField(default=0)),
                ('room_amount', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
