# Generated by Django 4.0.6 on 2022-09-30 08:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_en',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ru',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
    ]
