# Generated by Django 4.0.6 on 2022-10-06 18:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rooms_description_en_rooms_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='description_af',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ar_dz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ast',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_be',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_bg',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_bn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_bs',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ca',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_cs',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_cy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_da',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_dsb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_el',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_en_au',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_en_gb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_eo',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_es_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_es_co',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_es_mx',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_es_ni',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_es_ve',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_et',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_eu',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_fi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_fy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ga',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_gd',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_gl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_he',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_hi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_hr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_hsb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_hu',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ia',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ig',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ind',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_io',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_is',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ja',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ka',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_kab',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_km',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_kn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ko',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ky',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_lb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_lt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_lv',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_mk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ml',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_mn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_mr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ms',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_my',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_nb',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ne',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_nl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_nn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_os',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_pa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_pl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_pt_br',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ro',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_sk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_sl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_sq',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_sr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_sr_latn',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_sv',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_sw',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ta',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_te',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_tg',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_th',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_tk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_tt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_udm',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ur',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_vi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_zh_hans',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_zh_hant',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_af',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ar',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ar_dz',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ast',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_az',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_be',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_bg',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_bn',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_br',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_bs',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ca',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_cs',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_cy',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_da',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_de',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_dsb',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_el',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_en_au',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_en_gb',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_eo',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_es',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_es_ar',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_es_co',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_es_mx',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_es_ni',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_es_ve',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_et',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_eu',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_fa',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_fi',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_fr',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_fy',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ga',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_gd',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_gl',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_he',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_hi',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_hr',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_hsb',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_hu',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_hy',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ia',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ig',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ind',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_io',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_is',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_it',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ja',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ka',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_kab',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_kk',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_km',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_kn',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ko',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ky',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_lb',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_lt',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_lv',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_mk',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ml',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_mn',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_mr',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ms',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_my',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_nb',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ne',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_nl',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_nn',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_os',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_pa',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_pl',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_pt',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_pt_br',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ro',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_sk',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_sl',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_sq',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_sr',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_sr_latn',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_sv',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_sw',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ta',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_te',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_tg',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_th',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_tk',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_tr',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_tt',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_udm',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_uk',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_ur',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_uz',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_vi',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_zh_hans',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_zh_hant',
            field=models.CharField(choices=[('Junior Suite', 'Junior Suite'), ('Family Room', 'Family Room'), ('Double Room', 'Double Room'), ('Deluxe Room', 'Deluxe Room'), ('Superior Room', 'Superior Room')], max_length=100, null=True),
        ),
    ]
